/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessIndexRouteImport } from './routes/success.index'
import { Route as ShortsIndexRouteImport } from './routes/shorts.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CategoryCatslugIndexRouteImport } from './routes/category.$catslug.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as SuccessPagePageRouteImport } from './routes/success.page.$page'
import { Route as ShortsPagePageRouteImport } from './routes/shorts.page.$page'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as CategoryCatslugPagePageRouteImport } from './routes/category.$catslug.page.$page'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsIndexRoute = ShortsIndexRouteImport.update({
  id: '/shorts/',
  path: '/shorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoryCatslugIndexRoute = CategoryCatslugIndexRouteImport.update({
  id: '/category/$catslug/',
  path: '/category/$catslug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuccessPagePageRoute = SuccessPagePageRouteImport.update({
  id: '/success/page/$page',
  path: '/success/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsPagePageRoute = ShortsPagePageRouteImport.update({
  id: '/shorts/page/$page',
  path: '/shorts/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoryCatslugPagePageRoute = CategoryCatslugPagePageRouteImport.update({
  id: '/category/$catslug/page/$page',
  path: '/category/$catslug/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/shorts/': typeof ShortsIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/shorts/page/$page': typeof ShortsPagePageRoute
  '/success/page/$page': typeof SuccessPagePageRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/category/$catslug/': typeof CategoryCatslugIndexRoute
  '/category/$catslug/page/$page': typeof CategoryCatslugPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/shorts': typeof ShortsIndexRoute
  '/success': typeof SuccessIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/shorts/page/$page': typeof ShortsPagePageRoute
  '/success/page/$page': typeof SuccessPagePageRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/category/$catslug': typeof CategoryCatslugIndexRoute
  '/category/$catslug/page/$page': typeof CategoryCatslugPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/shorts/': typeof ShortsIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/shorts/page/$page': typeof ShortsPagePageRoute
  '/success/page/$page': typeof SuccessPagePageRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/category/$catslug/': typeof CategoryCatslugIndexRoute
  '/category/$catslug/page/$page': typeof CategoryCatslugPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
    | '/shorts/'
    | '/success/'
    | '/admin/posts/$id'
    | '/shorts/page/$page'
    | '/success/page/$page'
    | '/admin/posts/'
    | '/category/$catslug/'
    | '/category/$catslug/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin/login'
    | '/admin/users'
    | '/admin'
    | '/shorts'
    | '/success'
    | '/admin/posts/$id'
    | '/shorts/page/$page'
    | '/success/page/$page'
    | '/admin/posts'
    | '/category/$catslug'
    | '/category/$catslug/page/$page'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
    | '/shorts/'
    | '/success/'
    | '/admin/posts/$id'
    | '/shorts/page/$page'
    | '/success/page/$page'
    | '/admin/posts/'
    | '/category/$catslug/'
    | '/category/$catslug/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ShortsIndexRoute: typeof ShortsIndexRoute
  SuccessIndexRoute: typeof SuccessIndexRoute
  ShortsPagePageRoute: typeof ShortsPagePageRoute
  SuccessPagePageRoute: typeof SuccessPagePageRoute
  CategoryCatslugIndexRoute: typeof CategoryCatslugIndexRoute
  CategoryCatslugPagePageRoute: typeof CategoryCatslugPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/': {
      id: '/success/'
      path: '/success'
      fullPath: '/success/'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/': {
      id: '/shorts/'
      path: '/shorts'
      fullPath: '/shorts/'
      preLoaderRoute: typeof ShortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/category/$catslug/': {
      id: '/category/$catslug/'
      path: '/category/$catslug'
      fullPath: '/category/$catslug/'
      preLoaderRoute: typeof CategoryCatslugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/success/page/$page': {
      id: '/success/page/$page'
      path: '/success/page/$page'
      fullPath: '/success/page/$page'
      preLoaderRoute: typeof SuccessPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/page/$page': {
      id: '/shorts/page/$page'
      path: '/shorts/page/$page'
      fullPath: '/shorts/page/$page'
      preLoaderRoute: typeof ShortsPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/category/$catslug/page/$page': {
      id: '/category/$catslug/page/$page'
      path: '/category/$catslug/page/$page'
      fullPath: '/category/$catslug/page/$page'
      preLoaderRoute: typeof CategoryCatslugPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ShortsIndexRoute: ShortsIndexRoute,
  SuccessIndexRoute: SuccessIndexRoute,
  ShortsPagePageRoute: ShortsPagePageRoute,
  SuccessPagePageRoute: SuccessPagePageRoute,
  CategoryCatslugIndexRoute: CategoryCatslugIndexRoute,
  CategoryCatslugPagePageRoute: CategoryCatslugPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
